'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabase } from '../../lib/supabase';

export default function SessionResponsePage(){
  const [user,setUser]=useState<any>(null); const [session,setSession]=useState<any>(null); const [saved,setSaved]=useState(false);
  const [rpe,setRpe]=useState(6); const [feeling,setFeeling]=useState('bien'); const [pain,setPain]=useState(0); const [gi,setGi]=useState(0); const [carbs,setCarbs]=useState(''); const [fluid,setFluid]=useState(''); const [notes,setNotes]=useState('');
  useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();setUser(user);if(!user)return;const {data}=await supabase.from('training_sessions').select('*').eq('athlete_id',user.id).order('started_at',{ascending:false}).limit(1).maybeSingle();setSession(data);})();},[]);
  const response=useMemo(()=>{let score=100-rpe*5-pain*8-gi*4;if(session?.tss>90)score-=8;if(session?.training_load>220)score-=8;let label='POSITIVE';if(score<45)label='POOR RESPONSE';else if(score<65)label='COSTLY';else if(score<82)label='EXPECTED';const confidence=Math.min(92,55+[session?.avg_hr,session?.avg_power,session?.tss,session?.training_load].filter(v=>v!=null).length*8);return{score,label,confidence};},[rpe,pain,gi,session]);
  async function save(){if(!user)return;await supabase.from('session_responses').insert({athlete_id:user.id,training_session_id:session?.id??null,responded_at:new Date().toISOString(),rpe,feeling,avg_hr_bpm:session?.avg_hr??null,avg_power_w:session?.avg_power??null,tss:session?.tss??null,training_load:session?.training_load??null,carbs_g:carbs?Number(carbs):null,fluid_ml:fluid?Number(fluid):null,gi_score:gi,pain_score:pain,response_label:response.label,confidence_pct:response.confidence,why:[`RPE ${rpe}/10`,`Dolor ${pain}/10`,`GI ${gi}/10`,session?.tss?`TSS ${session.tss}`:'Carga automática disponible'],notes,source:'peppe-session-response-v1'});setSaved(true);}
  return <main className="shell"><header className="topbar"><div><span className="eyebrow">PEPPE · SESSION RESPONSE</span><h1>{response.label}</h1><p className="muted">La respuesta real del cuerpo cierra el ciclo de aprendizaje.</p></div><Link className="ghost link-button" href="/decision">Decision Engine</Link></header>
    <section className="grid content"><article className="card"><span className="eyebrow">SESIÓN DETECTADA</span><h2>{session?.title||'Último entrenamiento'}</h2><p>{session?.distance_m?`${(session.distance_m/1000).toFixed(1)} km · `:''}{session?.duration_seconds?`${Math.round(session.duration_seconds/60)} min`:''}</p><div className="metrics"><span>FC {session?.avg_hr??'—'}</span><span>Potencia {session?.avg_power??'—'}</span><span>TSS {session?.tss??'—'}</span><span>Carga {session?.training_load??'—'}</span></div></article><article className="card"><span className="eyebrow">LECTURA</span><h2>{response.label}</h2><p>Confianza {response.confidence}%</p><p>El sistema combina datos automáticos con las señales humanas que no entrega el dispositivo.</p></article></section>
    <section className="card"><span className="eyebrow">SOLO LO QUE FALTA</span><h2>Respuesta subjetiva</h2><div className="form-grid"><label>RPE 1–10<input type="number" min="1" max="10" value={rpe} onChange={e=>setRpe(Number(e.target.value))}/></label><label>Sensación<select value={feeling} onChange={e=>setFeeling(e.target.value)}><option value="excelente">Excelente</option><option value="bien">Bien</option><option value="normal">Normal</option><option value="pesado">Pesado</option><option value="mal">Mal</option></select></label><label>Dolor 0–10<input type="number" min="0" max="10" value={pain} onChange={e=>setPain(Number(e.target.value))}/></label><label>GI 0–10<input type="number" min="0" max="10" value={gi} onChange={e=>setGi(Number(e.target.value))}/></label><label>Carbohidratos durante (g)<input value={carbs} onChange={e=>setCarbs(e.target.value)} inputMode="decimal"/></label><label>Líquido durante (ml)<input value={fluid} onChange={e=>setFluid(e.target.value)} inputMode="decimal"/></label><label className="full">Notas<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><button className="primary wide" onClick={save}>{saved?'Session Response guardado':'Guardar Session Response'}</button></section>
    <section className="card"><span className="eyebrow">APRENDIZAJE</span><h2>Decisión → ejecución → respuesta</h2><p>Este registro queda disponible para comparar sesiones similares y mejorar futuras recomendaciones.</p><Link className="link-button ghost" href="/history">Ver historial</Link></section>
  </main>;
}
